// Server-only exports — may import Node.js modules, Anthropic SDK, etc.
export { chat } from './chat/chat-service'
export type { ChatResponse, Citation, ToolResult } from './chat/types'
export { runCostGuard } from './occupancy/cost-guard'
export type { RebalanceSuggestion, ProposedCut } from './occupancy/cost-guard'
export { RuleOverrideService } from './overrides/rule-override-service'
export { OVERRIDE_AUTHORISATION } from './overrides/authorisation'
export type { OverrideAuthorisation } from './overrides/authorisation'
export type { RecordOverrideParams } from './overrides/rule-override-service'
export { recordAudit } from './audit/audit-service'
export type { RecordAuditParams } from './audit/audit-service'
export { checkShiftEligibility } from './rota/eligibility-check'
export type { EligibilityResult, RuleBlock, OverridePath } from './rota/eligibility-check'
export { createRotaPeriod } from './rota/period-create'
export type { CreatePeriodResult } from './rota/period-create'
export { publishRotaPeriod } from './rota/publish'
export type { PublishResult, PublishBlock } from './rota/publish'
export { autoFillPeriod } from './rota/auto-fill'
export type { AutoFillResult } from './rota/auto-fill'
export { generateHorizon, periodsToCover } from './rota/generate-horizon'
export type { GenerateHorizonResult } from './rota/generate-horizon'
export { computeLeaveAccrual, ACCRUAL_RATE_12_07 } from './leave/accrual'
export type { HolidayAccrualModel } from './leave/accrual'
export { raiseRebalanceSuggestion } from './leave/rebalance'
export type { RebalanceTrigger, RebalanceSuggestionResult } from './leave/rebalance'
